[package]
name = "luminous"
version = "0.1.0"
edition = "2024"

[dependencies]
oci-spec = "0.8.1"
axum = "0.8.4"
tokio = { version = "1.45.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }

