name: conformance-action

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Start a test registry (zot)
        run: |
          set -x
          make registry-ci
      - name: Run OCI distribution-spec conformance
        env:
          OCI_ROOT_URL: http://localhost:5000
          OCI_NAMESPACE: myorg/myrepo
          OCI_TEST_PULL: 1
          OCI_TEST_PUSH: 1
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_TEST_CONTENT_MANAGEMENT: 1
        uses: ./
